"""
Vocabulaire de reconnaissance ClearVision.

Pour ajouter un objet ou un animal :
1. Ajoutez le prompt anglais dans la liste correspondante ci-dessous.
2. Ajoutez la traduction française dans LABEL_FR.
3. (Optionnel) Ajoutez une hauteur dans clearvision_voice.REAL_HEIGHT_M pour la voix.
"""

# --- Animaux : mammifères domestiques et de ferme ---
ANIMALS_DOMESTIC = [
    "dog",
    "puppy",
    "cat",
    "kitten",
    "hamster",
    "guinea pig",
    "rabbit",
    "ferret",
    "chinchilla",
    "horse",
    "pony",
    "donkey",
    "cow",
    "calf",
    "sheep",
    "lamb",
    "goat",
    "pig",
    "chicken",
    "rooster",
    "duck",
    "goose",
    "turkey",
    "llama",
    "alpaca",
]

# --- Animaux : mammifères sauvages ---
ANIMALS_WILD_MAMMALS = [
    "deer",
    "moose",
    "elk",
    "bear",
    "wolf",
    "fox",
    "raccoon",
    "squirrel",
    "chipmunk",
    "hedgehog",
    "badger",
    "otter",
    "beaver",
    "bat",
    "kangaroo",
    "koala",
    "panda",
    "zebra",
    "giraffe",
    "rhinoceros",
    "hippopotamus",
    "camel",
    "elephant",
    "lion",
    "tiger",
    "leopard",
    "cheetah",
    "jaguar",
    "hyena",
    "monkey",
    "gorilla",
    "wild boar",
    "seal",
    "walrus",
]

# --- Animaux : oiseaux ---
ANIMALS_BIRDS = [
    "bird",
    "eagle",
    "hawk",
    "falcon",
    "owl",
    "crow",
    "raven",
    "pigeon",
    "dove",
    "sparrow",
    "robin",
    "parrot",
    "macaw",
    "cockatoo",
    "peacock",
    "flamingo",
    "swan",
    "pelican",
    "seagull",
    "woodpecker",
    "hummingbird",
    "penguin",
    "ostrich",
]

# --- Animaux : reptiles, amphibiens, poissons, insectes ---
ANIMALS_OTHER = [
    "snake",
    "lizard",
    "crocodile",
    "alligator",
    "turtle",
    "tortoise",
    "frog",
    "toad",
    "salamander",
    "chameleon",
    "iguana",
    "fish",
    "goldfish",
    "shark",
    "dolphin",
    "whale",
    "octopus",
    "jellyfish",
    "crab",
    "lobster",
    "shrimp",
    "starfish",
    "seahorse",
    "butterfly",
    "bee",
    "wasp",
    "ant",
    "beetle",
    "dragonfly",
    "mosquito",
    "fly",
    "grasshopper",
    "caterpillar",
    "ladybug",
    "insect",
    "spider",
    "scorpion",
]

WORLD_ANIMAL_CLASSES = (
    ANIMALS_DOMESTIC + ANIMALS_WILD_MAMMALS + ANIMALS_BIRDS + ANIMALS_OTHER
)

# --- Plantes et végétation ---
PLANTS_TREES = [
    "tree",
    "tree in park",
    "evergreen tree",
    "street tree",
    "forest tree",
    "oak tree",
    "pine tree",
    "palm tree",
    "birch tree",
    "maple tree",
    "willow tree",
    "fruit tree",
    "apple tree",
    "cherry tree",
]

PLANTS_SHRUBS = [
    "green bush",
    "shrub",
    "hedge",
    "hedge row",
    "foliage",
    "ivy",
    "vine",
    "bamboo",
    "moss",
]

PLANTS_FLOWERS = [
    "flower",
    "rose",
    "tulip",
    "sunflower",
    "daisy",
    "orchid",
    "lavender",
    "dandelion",
    "bouquet",
]

PLANTS_OTHER = [
    "grass",
    "meadow",
    "potted plant",
    "houseplant",
    "fern",
    "cactus",
    "succulent",
    "mushroom",
    "vegetable plant",
    "wheat field",
    "corn field",
    "garden",
]

WORLD_PLANT_CLASSES = PLANTS_TREES + PLANTS_SHRUBS + PLANTS_FLOWERS + PLANTS_OTHER

# Alias utilisé par la détection végétation HSV / World
VEGETATION_CLASSES = WORLD_PLANT_CLASSES

# --- Objets : électronique et bureau ---
OBJECTS_ELECTRONICS = [
    "laptop",
    "computer",
    "monitor",
    "keyboard",
    "mouse",
    "phone",
    "smartphone",
    "tablet",
    "camera",
    "headphones",
    "speaker",
    "microphone",
    "printer",
    "router",
    "remote",
    "game controller",
    "television",
    "tv",
]

# --- Objets : cuisine et nourriture ---
OBJECTS_KITCHEN = [
    "cup",
    "mug",
    "glass",
    "bottle",
    "wine glass",
    "plate",
    "bowl",
    "fork",
    "knife",
    "spoon",
    "pot",
    "pan",
    "kettle",
    "microwave",
    "oven",
    "refrigerator",
    "toaster",
    "blender",
    "sink",
    "apple",
    "banana",
    "orange",
    "bread",
    "pizza",
    "cake",
    "sandwich",
]

# --- Objets : maison et mobilier ---
OBJECTS_HOME = [
    "chair",
    "armchair",
    "sofa",
    "couch",
    "table",
    "desk",
    "bed",
    "pillow",
    "blanket",
    "lamp",
    "clock",
    "mirror",
    "curtain",
    "rug",
    "carpet",
    "vase",
    "candle",
    "bookshelf",
    "wardrobe",
    "door",
    "window",
    "toilet",
    "bathtub",
    "shower",
]

# --- Objets : vêtements, sacs, accessoires ---
OBJECTS_PERSONAL = [
    "backpack",
    "handbag",
    "suitcase",
    "wallet",
    "hat",
    "cap",
    "glasses",
    "sunglasses",
    "watch",
    "ring",
    "necklace",
    "shoe",
    "sneaker",
    "boot",
    "jacket",
    "coat",
    "umbrella",
    "scarf",
    "gloves",
]

# --- Objets : loisirs, outils, divers ---
OBJECTS_MISC = [
    "book",
    "notebook",
    "pen",
    "pencil",
    "scissors",
    "toothbrush",
    "toothpaste",
    "comb",
    "hair dryer",
    "teddy bear",
    "toy",
    "doll",
    "ball",
    "football",
    "basketball",
    "tennis racket",
    "guitar",
    "piano",
    "violin",
    "skateboard",
    "bicycle",
    "scooter",
    "hammer",
    "screwdriver",
    "wrench",
    "drill",
    "ladder",
    "bucket",
    "broom",
    "mop",
    "fire extinguisher",
    "traffic light",
    "parking meter",
    "bench",
    "wheelchair",
    "stroller",
    "crutch",
]

WORLD_OBJECT_CLASSES = (
    OBJECTS_ELECTRONICS + OBJECTS_KITCHEN + OBJECTS_HOME + OBJECTS_PERSONAL + OBJECTS_MISC
)

# --- Traductions françaises ---
LABEL_FR = {
    # Animaux domestiques
    "dog": "Chien",
    "puppy": "Chiot",
    "cat": "Chat",
    "kitten": "Chaton",
    "hamster": "Hamster",
    "guinea pig": "Cochon d'Inde",
    "rabbit": "Lapin",
    "ferret": "Furet",
    "chinchilla": "Chinchilla",
    "horse": "Cheval",
    "pony": "Poney",
    "donkey": "Âne",
    "cow": "Vache",
    "calf": "Veau",
    "sheep": "Mouton",
    "lamb": "Agneau",
    "goat": "Chèvre",
    "pig": "Cochon",
    "chicken": "Poule",
    "rooster": "Coq",
    "duck": "Canard",
    "goose": "Oie",
    "turkey": "Dinde",
    "llama": "Lama",
    "alpaca": "Alpaga",
    # Animaux sauvages
    "deer": "Cerf",
    "moose": "Élan",
    "elk": "Wapiti",
    "bear": "Ours",
    "wolf": "Loup",
    "fox": "Renard",
    "raccoon": "Raton laveur",
    "squirrel": "Écureuil",
    "chipmunk": "Tamia",
    "hedgehog": "Hérisson",
    "badger": "Blaireau",
    "otter": "Loutre",
    "beaver": "Castor",
    "bat": "Chauve-souris",
    "kangaroo": "Kangourou",
    "koala": "Koala",
    "panda": "Panda",
    "zebra": "Zèbre",
    "giraffe": "Girafe",
    "rhinoceros": "Rhinocéros",
    "hippopotamus": "Hippopotame",
    "camel": "Chameau",
    "elephant": "Éléphant",
    "lion": "Lion",
    "tiger": "Tigre",
    "leopard": "Léopard",
    "cheetah": "Guépard",
    "jaguar": "Jaguar",
    "hyena": "Hyène",
    "monkey": "Singe",
    "gorilla": "Gorille",
    "wild boar": "Sanglier",
    "seal": "Phoque",
    "walrus": "Morse",
    # Oiseaux
    "bird": "Oiseau",
    "eagle": "Aigle",
    "hawk": "Faucon",
    "falcon": "Faucon",
    "owl": "Hibou",
    "crow": "Corbeau",
    "raven": "Corbeau",
    "pigeon": "Pigeon",
    "dove": "Colombe",
    "sparrow": "Moineau",
    "robin": "Rouge-gorge",
    "parrot": "Perroquet",
    "macaw": "Ara",
    "cockatoo": "Cacatoès",
    "peacock": "Paon",
    "flamingo": "Flamant rose",
    "swan": "Cygne",
    "pelican": "Pélican",
    "seagull": "Mouette",
    "woodpecker": "Pic",
    "hummingbird": "Colibri",
    "penguin": "Manchot",
    "ostrich": "Autruche",
    # Autres animaux
    "snake": "Serpent",
    "lizard": "Lézard",
    "crocodile": "Crocodile",
    "alligator": "Alligator",
    "turtle": "Tortue",
    "tortoise": "Tortue terrestre",
    "frog": "Grenouille",
    "toad": "Crapaud",
    "salamander": "Salamandre",
    "chameleon": "Caméléon",
    "iguana": "Iguane",
    "fish": "Poisson",
    "goldfish": "Poisson rouge",
    "shark": "Requin",
    "dolphin": "Dauphin",
    "whale": "Baleine",
    "octopus": "Poulpe",
    "jellyfish": "Méduse",
    "crab": "Crabe",
    "lobster": "Homard",
    "shrimp": "Crevette",
    "starfish": "Étoile de mer",
    "seahorse": "Hippocampe",
    "butterfly": "Papillon",
    "bee": "Abeille",
    "wasp": "Guêpe",
    "ant": "Fourmi",
    "beetle": "Scarabée",
    "dragonfly": "Libellule",
    "mosquito": "Moustique",
    "fly": "Mouche",
    "grasshopper": "Sauterelle",
    "caterpillar": "Chenille",
    "ladybug": "Coccinelle",
    "insect": "Insecte",
    "spider": "Araignée",
    "scorpion": "Scorpion",
    # Plantes
    "tree": "Arbre",
    "tree in park": "Arbre",
    "evergreen tree": "Arbre",
    "street tree": "Arbre",
    "forest tree": "Arbre",
    "oak tree": "Chêne",
    "pine tree": "Pin",
    "palm tree": "Palmier",
    "birch tree": "Bouleau",
    "maple tree": "Érable",
    "willow tree": "Saule",
    "fruit tree": "Arbre fruitier",
    "apple tree": "Pommier",
    "cherry tree": "Cerisier",
    "green bush": "Buisson",
    "shrub": "Arbuste",
    "hedge": "Haie",
    "hedge row": "Haie",
    "foliage": "Végétation",
    "ivy": "Lierre",
    "vine": "Vigne",
    "bamboo": "Bambou",
    "moss": "Mousse",
    "flower": "Fleur",
    "rose": "Rose",
    "tulip": "Tulipe",
    "sunflower": "Tournesol",
    "daisy": "Pâquerette",
    "orchid": "Orchidée",
    "lavender": "Lavande",
    "dandelion": "Pissenlit",
    "bouquet": "Bouquet",
    "grass": "Herbe",
    "meadow": "Prairie",
    "potted plant": "Plante en pot",
    "houseplant": "Plante d'intérieur",
    "fern": "Fougère",
    "cactus": "Cactus",
    "succulent": "Plante succulente",
    "mushroom": "Champignon",
    "vegetable plant": "Plante potagère",
    "wheat field": "Champ de blé",
    "corn field": "Champ de maïs",
    "garden": "Jardin",
    "hsv": "Végétation",
    "tree_line": "Arbre",
    # Objets électronique
    "laptop": "Ordinateur portable",
    "computer": "Ordinateur",
    "monitor": "Écran",
    "keyboard": "Clavier",
    "mouse": "Souris",
    "phone": "Téléphone",
    "smartphone": "Smartphone",
    "tablet": "Tablette",
    "camera": "Appareil photo",
    "headphones": "Casque audio",
    "speaker": "Enceinte",
    "microphone": "Microphone",
    "printer": "Imprimante",
    "router": "Routeur",
    "remote": "Télécommande",
    "game controller": "Manette de jeu",
    "television": "Télévision",
    "tv": "Télévision",
    # Cuisine
    "cup": "Tasse",
    "mug": "Mug",
    "glass": "Verre",
    "bottle": "Bouteille",
    "wine glass": "Verre à vin",
    "plate": "Assiette",
    "bowl": "Bol",
    "fork": "Fourchette",
    "knife": "Couteau",
    "spoon": "Cuillère",
    "pot": "Casserole",
    "pan": "Poêle",
    "kettle": "Bouilloire",
    "microwave": "Micro-ondes",
    "oven": "Four",
    "refrigerator": "Réfrigérateur",
    "toaster": "Grille-pain",
    "blender": "Mixeur",
    "sink": "Évier",
    "apple": "Pomme",
    "banana": "Banane",
    "orange": "Orange",
    "bread": "Pain",
    "pizza": "Pizza",
    "cake": "Gâteau",
    "sandwich": "Sandwich",
    # Maison
    "chair": "Chaise",
    "armchair": "Fauteuil",
    "sofa": "Canapé",
    "couch": "Canapé",
    "table": "Table",
    "desk": "Bureau",
    "bed": "Lit",
    "pillow": "Oreiller",
    "blanket": "Couverture",
    "lamp": "Lampe",
    "clock": "Horloge",
    "mirror": "Miroir",
    "curtain": "Rideau",
    "rug": "Tapis",
    "carpet": "Moquette",
    "vase": "Vase",
    "candle": "Bougie",
    "bookshelf": "Bibliothèque",
    "wardrobe": "Armoire",
    "door": "Porte",
    "window": "Fenêtre",
    "toilet": "Toilettes",
    "bathtub": "Baignoire",
    "shower": "Douche",
    # Personnel
    "backpack": "Sac à dos",
    "handbag": "Sac à main",
    "suitcase": "Valise",
    "wallet": "Portefeuille",
    "hat": "Chapeau",
    "cap": "Casquette",
    "glasses": "Lunettes",
    "sunglasses": "Lunettes de soleil",
    "watch": "Montre",
    "ring": "Bague",
    "necklace": "Collier",
    "shoe": "Chaussure",
    "sneaker": "Basket",
    "boot": "Botte",
    "jacket": "Veste",
    "coat": "Manteau",
    "umbrella": "Parapluie",
    "scarf": "Écharpe",
    "gloves": "Gants",
    # Divers
    "book": "Livre",
    "notebook": "Carnet",
    "pen": "Stylo",
    "pencil": "Crayon",
    "scissors": "Ciseaux",
    "toothbrush": "Brosse à dents",
    "toothpaste": "Dentifrice",
    "comb": "Peigne",
    "hair dryer": "Sèche-cheveux",
    "teddy bear": "Peluche",
    "toy": "Jouet",
    "doll": "Poupée",
    "ball": "Balle",
    "football": "Ballon de football",
    "basketball": "Ballon de basket",
    "tennis racket": "Raquette de tennis",
    "guitar": "Guitare",
    "piano": "Piano",
    "violin": "Violon",
    "skateboard": "Skateboard",
    "bicycle": "Vélo",
    "scooter": "Trottinette",
    "hammer": "Marteau",
    "screwdriver": "Tournevis",
    "wrench": "Clé",
    "drill": "Perceuse",
    "ladder": "Échelle",
    "bucket": "Seau",
    "broom": "Balai",
    "mop": "Serpillière",
    "fire extinguisher": "Extincteur",
    "traffic light": "Feu tricolore",
    "parking meter": "Parcmètre",
    "bench": "Banc",
    "wheelchair": "Fauteuil roulant",
    "stroller": "Poussette",
    "crutch": "Béquille",
}
